Spark standalone mode
Yodafon/GeocacheGrouping pull request #2
Opened 2023-08-30 10:59 UTC by Yodafon

2023-08-30 18:39 UTC, vilinet requested changes

2023-08-30 18:39 UTC, vilinet commented on GeocachingGrouping/build.gradle
> +    } {
Ugli!

2023-08-30 18:39 UTC, vilinet commented on GeocachingGrouping/build.gradle
> +
Will you ever need it?

2023-09-01 08:00 UTC, Yodafon commented on GeocachingGrouping/build.gradle
> +
Spark has two different modes: Local mode and standalone mode, this dependency list is for standalone mode. In cloud or on any dedicated servers the standalone mode is the best approach.

2023-09-01 08:01 UTC, Yodafon commented on GeocachingGrouping/build.gradle
> +    } {
why? Suggestion?

2023-09-01 10:21 UTC, vilinet approved these changes

2023-09-01 11:14 UTC, merged