Add Hazelcast support, load with REST and put into cache the regions …
Yodafon/GeocacheGrouping pull request #3
Opened 2023-08-30 10:59 UTC by Yodafon

…by counties, enrich geocaches with regions, add bean creation order by DependsOn annotations to be populated the cache first

2023-08-30 18:38 UTC, vilinet requested changes

2023-08-30 18:38 UTC, vilinet commented on GeocachingLoader/src/com/gg/loader/cache/RegionCache.java
> +        Map<String, String> regionList = nuts.getObjects().getNUTSLB20214326().getGeometries().stream().map(item -> item.getProperties())
Could be moved into a variable and use that instead of using it twice: `nuts.getObjects().getNUTSLB20214326().getGeometries().stream().map(item -> item.getProperties())`

2023-09-01 08:11 UTC, Yodafon commented on GeocachingLoader/src/com/gg/loader/cache/RegionCache.java
> +        Map<String, String> regionList = nuts.getObjects().getNUTSLB20214326().getGeometries().stream().map(item -> item.getProperties())
Unfortunately streams can't be used twice. 
I can extract this part:
`        List<Geometries> geometries = nuts.getObjects().getNUTSLB20214326().getGeometries();
`

2023-09-02 10:13 UTC, vilinet approved these changes

2023-09-02 15:57 UTC, merged