Fix url in GeocachingPoller script
Yodafon/GeocacheGrouping pull request #5
Opened 2023-08-30 10:59 UTC by Yodafon

2023-08-30 18:30 UTC, vilinet requested changes

2023-08-30 18:30 UTC, vilinet commented on scripts/GeocachePoller.py
> +            "https://www.geocaching.hu/caches.geo?egylapon=25&dist_lat=&dist_lon=&filetype=gpx_groundspeak_uj&wp_logs_max=&waypoint_xml=%3Cfield+name%3D%22kod%22+deaccent%3D%22i%22+case%3D%22upper%22
Will it ever change? Could be moved into config file maybe :P

2023-09-01 09:17 UTC, Yodafon commented on scripts/GeocachePoller.py
> +            "https://www.geocaching.hu/caches.geo?egylapon=25&dist_lat=&dist_lon=&filetype=gpx_groundspeak_uj&wp_logs_max=&waypoint_xml=%3Cfield+name%3D%22kod%22+deaccent%3D%22i%22+case%3D%22upper%22
Moved into property file

2023-09-01 10:20 UTC, vilinet approved these changes

2023-09-01 11:14 UTC, merged